version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - vacation-network
  
  backend:
    depends_on:
      - mysqldb
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - vacation-network


  frontend:
    container_name: vacation_frontend
    image: vacation_frontend:1.0.0
    build: 
      context: frontend
      # target: production
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    networks:
      - vacation-network
    depends_on:
      - backend

networks:
  vacation-network:
    driver: bridge  

volumes: 
  db:

